import { InterfaceStatus } from '../enums/interface-status.enum';
import { AccountLineType } from './account-line-type.entity';
import { AccountType } from './account-type.entity';
import { AddressType } from './address-type.entity';
import { Arbitration } from './arbitration.entity';
import { BankAccountStatus } from './bank-account-status.entity';
import { BankNccType } from './bank-ncc-type.entity';
import { BankType } from './bank-type.entity';
import { Broker } from './broker.entity';
import { BusinessSector } from './business-sector-entity';
import { CashTypes } from './cash-type.entity';
import { Commodity } from './commodity.entity';
import { CommodityTypes } from './commodityTypes.entity';
import { Company } from './company.entity';
import { ContractTerm } from './contract-term.entity';
import { CostDirection } from './cost-direction.entity';
import { CostPriceCode } from './cost-price-code.entity';
import { CostType } from './cost-type.entity';
import { CounterpartyBankAccounts } from './counterparty-bankaccounts.entity';
import { CounterpartyTradeStatus } from './counterparty-trade-status.entity';
import { Counterparty } from './counterparty.entity';
import { Country } from './country.entity';
import { Currency } from './currency.entity';
import { DateFormat } from './date-format.entity';
import { Department } from './department.entity';
import { PhysicalDocumentType } from './document-type.entity';
import { EnumEntity } from './enum-entity.entity';
import { ExpenseCode } from './expense-code.entity';
import { FixType } from './fix-type.entity';
import { ForeignExchangeRate } from './foreign-exchange/foreign-exchange-rate.entity';
import { FuturesOptionsCommodity } from './futures-options-commodity.entity';
import { FxTradeType } from './fx-trade-type.entity';
import { InterfaceTypes } from './interface-type.entity';
import { InterfaceObjectTypes } from './interface-object-type.entity';
import { InvoiceStatus } from './invoice-status.entity';
import { InvoiceType } from './invoice-type.entity';
import { Language } from './language.entity';
import { LdcRegion } from './ldc-region.entity';
import { MdmCategory } from './mdm-Category.entity';
import { NominalAccount } from './nominal-account.entity';
import { Packing } from './packing.entity';
import { PaymentTerm } from './payment-term.entity';
import { PeriodType } from './period-type.entity';
import { PNLType } from './pnl-type.entity';
import { Port } from './port.entity';
import { PositionMonthType } from './position-month-type.entity';
import { PriceUnit } from './price-unit.entity';
import { PricingOptions } from './pricing-options.entity';
import { ProcessStatus } from './process-status.entity';
import { ProfitCenter } from './profit-center.entity';
import { Province } from './province.entity';
import { RateType } from './rate-type.entity';
import { ShippingStatus } from './shipping-status.entity';
import { TaxType } from './tax-Type.entity';
import { TimeZone } from './time-zone.entity';
import { ToleranceType } from './tolerance-type.entity';
import { TraderMasterData } from './trader-masterdata.entity';
import { transactionDocumentType } from './transaction-document-type.entity';
import { TransportType } from './transport-type.entity';
import { Vat } from './vat.entity';
import { Vessel } from './vessel.entity';
import { WeightUnit } from './weight-unit.entity';
import { TaxCode } from './tax-Code.entity';
import { Branch } from './branch.entity';

export class MasterData {
    arbitrations: Arbitration[];
    bankTypes: BankType[];
    shippingStatus: ShippingStatus[];
    bankNccTypes: BankNccType[];
    bankAccountStatuses: BankAccountStatus[];
    processStatuses: ProcessStatus[];
    nominalAccounts: NominalAccount[];
    cashTypes: CashTypes[];
    languagePreference: Language[];
    dateFormatPreference: DateFormat[];
    interfaceType: InterfaceTypes[];
    interfaceObjectType: InterfaceObjectTypes[];
    brokers: Broker[];
    commodities: Commodity[];
    commodityTypes: CommodityTypes[];
    companies: Company[];
    contractTerms: ContractTerm[];
    costPriceCodes: CostPriceCode[];
    costTypes: CostType[];
    costDirections: CostDirection[];
    counterparties: Counterparty[];
    countries: Country[];
    currencies: Currency[];
    departments: Department[];
    documentTypes: PhysicalDocumentType[];
    expenseCodes: ExpenseCode[];
    fixTypes: FixType[];
    futuresOptionsCommodities: FuturesOptionsCommodity[];
    foreignExchangeRate: ForeignExchangeRate[];
    futuresOptionsClients: Counterparty[];
    futuresOptionsBrokers: Counterparty[];
    fxRates: ForeignExchangeRate[];
    invoiceTypes: InvoiceType[];
    businessSectors: BusinessSector[];
    packings: Packing[];
    paymentTerms: PaymentTerm[];
    periodTypes: PeriodType[];
    pnlTypes: PNLType[];
    ports: Port[];
    positionMonthTypes: PositionMonthType[];
    weightUnits: WeightUnit[];
    rateTypes: RateType[];
    pricingOptions: PricingOptions[];
    invoiceStatus: InvoiceStatus[];
    toleranceTypes: ToleranceType[];
    traders: TraderMasterData[];
    transportTypes: TransportType[];
    vats: Vat[];
    vessels: Vessel[];
    priceUnits: PriceUnit[];
    counterpartyBankAccounts: CounterpartyBankAccounts[];
    profitCenters: ProfitCenter[];
    accountLineTypes: AccountLineType[];
    accountTypes: AccountType[];
    provinces: Province[];
    branches: Branch[];
    regions: LdcRegion[];
    tradeStatus: CounterpartyTradeStatus[];
    addressTypes: AddressType[];
    timeZones: TimeZone[];
    // -- Enums
    // contractType: EnumEntity[];
    contractStatus: EnumEntity[];
    contractTypes: EnumEntity[];
    postingStatus: EnumEntity[];
    booleanValues: EnumEntity[];
    physicalDocumentTypes: EnumEntity[];
    physicalDocumentStatus: EnumEntity[];
    ad: AddressType[];
    transactionDocumentType: transactionDocumentType[];
    transactionDocumentStatus: EnumEntity[];
    monthEndReportType: EnumEntity[];
    companyTypes: EnumEntity[];
    companyPlatforms: EnumEntity[];
    companyCropYearFormats: EnumEntity[];
    mdmCategories: MdmCategory[];
    taxTypes: TaxType[];
    fxTradeTypes: FxTradeType[];
    interfaceStatus: InterfaceStatus[];
    taxCode: TaxCode[];

    constructor() {
        this.arbitrations = [];
        this.bankTypes = [];
        this.shippingStatus = [];
        this.bankNccTypes = [];
        this.bankAccountStatuses = [];
        this.processStatuses = [];
        this.nominalAccounts = [];
        this.cashTypes = [];
        this.languagePreference = [];
        this.interfaceType = [];
        this.interfaceObjectType = [];
        this.brokers = [];
        this.commodities = [];
        this.commodityTypes = [];
        this.companies = [];
        this.contractTerms = [];
        this.costPriceCodes = [];
        this.costTypes = [];
        this.costDirections = [];
        this.counterparties = [];
        this.countries = [];
        this.currencies = [];
        this.departments = [];
        this.documentTypes = [];
        this.expenseCodes = [];
        this.fixTypes = [];
        this.dateFormatPreference = [];
        this.futuresOptionsCommodities = [];
        this.futuresOptionsClients = [];
        this.foreignExchangeRate = [];
        this.futuresOptionsBrokers = [];
        this.invoiceTypes = [];
        this.businessSectors = [];
        this.packings = [];
        this.paymentTerms = [];
        this.periodTypes = [];
        this.pnlTypes = [];
        this.ports = [];
        this.positionMonthTypes = [];
        this.weightUnits = [];
        this.rateTypes = [];
        this.pricingOptions = [];
        this.toleranceTypes = [];
        this.transportTypes = [];
        this.vats = [];
        this.vessels = [];
        this.priceUnits = [];
        this.invoiceStatus = [];
        this.fxRates = [];
        this.counterpartyBankAccounts = [];
        this.profitCenters = [];
        this.accountLineTypes = [];
        this.accountTypes = [];
        this.provinces = [];
        this.branches = [];
        this.regions = [];
        this.addressTypes = [];
        this.tradeStatus = [];
        this.timeZones = [];
        // -- Enums
        // this.contractType = [];
        this.contractStatus = [];
        this.contractTypes = [];
        this.postingStatus = [];
        this.booleanValues = [];
        this.physicalDocumentTypes = [];
        this.physicalDocumentStatus = [];
        this.transactionDocumentStatus = [];
        this.transactionDocumentType = [];
        this.monthEndReportType = [];
        this.mdmCategories = [];
        this.taxTypes = [];
        this.companyTypes = [];
        this.companyPlatforms = [];
        this.companyCropYearFormats = [];
        this.fxTradeTypes = [];
        this.interfaceStatus = [];
        this.taxCode = [];
        this.branches = [];
    }
}
